INSERT INTO ACCOUNT_GRANTED_AUTHORITY (ID, AUTHORITY) VALUES(1, 'ADMIN');

INSERT INTO ACCOUNT (ID, NICKNAME, ENABLED, EMAIL, PASSWORD) VALUES(1, 'jshuser', true, 'user@jsh.gob.mx', 'testpasswd');

INSERT INTO ACCOUNT_GRANTED_AUTHORITIES (ACCOUNT, AUTHORITY) VALUES(1,1);

